In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:

file = '/content/drive/My Drive/data/digits/files.txt'
path = '/content/drive/My Drive/data/digits'

###############################################################################
# Dummy Pixels
###############################################################################
import os
import cv2
import pandas as pd
import progressbar

w = 5
h = 5

X = []
y = []

listOfImages = []
  
arq = open(file)
lines = arq.readlines()


for line in  progressbar.progressbar(lines):
  aux = line.split('/')[1]
  image_name = aux.split(' ')[0]
  label = line.split(' ')[1]
  label = label.split('\n')
  
  f = path + '/data/' + image_name
  #print (f)
  
  ## opens the image using a single chanel (grey level)
  imagem = cv2.imread(f,0)
  
  listOfImages.append(f)
  
  ## rezise the image according to the parameters
  imagem = cv2.resize(imagem,(h,w))  #### <=====

  ## pixel count  
  v = []
  for i in range(w):
    for j in range(h):
      if(imagem[i][j] > 128):
        v.append(0)
      else:
        v.append(1)
  
  X.append(v)
  y.append(int(label[0]))
      
      
## Save data

            
# Saving the extracted features (handcrafted) in a csv file
print ('Saving data...')
df = pd.DataFrame(X)
df.to_csv('/content/drive/My Drive/data/X.csv', header=False, index=False)

# Saving the classes in a csv file
df_class = pd.DataFrame(y)
df_class.to_csv('/content/drive/My Drive/data/y.csv', header=False, index=False)

print ('Done!')

100% (2000 of 2000) |####################| Elapsed Time: 0:00:07 Time:  0:00:07


Saving data...
Done!


In [7]:
###############################################################################
## Classify using Holdout
###############################################################################
import pandas as pd
import numpy as np
from sklearn import  model_selection
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report


# Labels
y = pd.read_csv('/content/drive/My Drive/data/y.csv', header=None)
y=y.to_numpy()
y=np.ravel(y)
print(y.shape)

# Features
X = pd.read_csv('/content/drive/My Drive/data/X.csv', header=None)
X=X.to_numpy()
print(X.shape)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.5, random_state=42)

# Train the classifier
clfa = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
#clfa = LogisticRegression(C=1e5, solver='lbfgs', multi_class='multinomial')
clfa = clfa.fit(X_train, y_train)

# Predict
predicted=clfa.predict(X_test)
score=clfa.score(X_test, y_test)

matrix = confusion_matrix(y_test, predicted)

# Print results
print("Accuracy = %.2f " % score)
print("Confusion Matrix:")
print(matrix)

print(classification_report(y_test, predicted, labels=[0,1, 2, 3,4,5,6,7,8,9]))

(2000,)
(2000, 25)
Accuracy = 0.78 
Confusion Matrix:
[[ 91   1   0   1   0   0   0   0   0   0]
 [  1 107   2   0   0   0   1   0   1   0]
 [ 10   9  69   9   0   1   3   4   2   3]
 [  3   1   1  77   0   9   0   0   0   1]
 [  1  10   1   0  85   0   0   0   0   3]
 [  3   1   1   7   0  73   1   1   1   0]
 [  7   3   2   0   0   2  86   0   0   0]
 [  0   8   1   0   1   1   0  77   0  13]
 [  2   6   2  12   6   8   1   8  48   4]
 [  1   3   0   2   6   1   0  26   1  67]]
              precision    recall  f1-score   support

           0       0.76      0.98      0.86        93
           1       0.72      0.96      0.82       112
           2       0.87      0.63      0.73       110
           3       0.71      0.84      0.77        92
           4       0.87      0.85      0.86       100
           5       0.77      0.83      0.80        88
           6       0.93      0.86      0.90       100
           7       0.66      0.76      0.71       101
           8       0.91     